name: Run Benchmarks

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build TypeScript
      run: npm run build

    - name: Run benchmarks
      run: node dist/benchmark.js

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"

    - name: Create and switch to results branch
      run: |
        git checkout -b benchmark-results || git checkout benchmark-results
        git pull origin benchmark-results || true

    - name: Commit benchmark results
      run: |
        git add benchmark-results/
        git commit -m "Add benchmark results [skip ci]" || echo "No changes to commit"
        git push origin benchmark-results
